// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsu1QPp2g_NKo1ids-UB-r9LsnnDvrvcA',
    appId: '1:558675945291:web:efce0a8923c38dcede2ace',
    messagingSenderId: '558675945291',
    projectId: 'mychat-208d7',
    authDomain: 'mychat-208d7.firebaseapp.com',
    storageBucket: 'mychat-208d7.firebasestorage.app',
    measurementId: 'G-5KN3682RV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZ4QSIiAtyz518vhQUWbvmJ1qb2Ze7r4',
    appId: '1:558675945291:android:579d424c10644838de2ace',
    messagingSenderId: '558675945291',
    projectId: 'mychat-208d7',
    storageBucket: 'mychat-208d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIYjy3viLMnJ4NgpvLnxEh2DM47CfJKA',
    appId: '1:558675945291:ios:ce532e82c8671481de2ace',
    messagingSenderId: '558675945291',
    projectId: 'mychat-208d7',
    storageBucket: 'mychat-208d7.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );
}
